export const playerInfo = {
	"content_type_id" : 2,
	"player/age" : 30,
	"player/portait" : "/db/PICTURES/CMS/222900/222915.jpg",
	"player/dod" : "0000-00-00",
	"player/bowling-styles" : "right-arm offbreak",
	"player/teams" : ["INDIA"],
	"player/retired?" : "N",
	"player/name" : "RG Sharma",
	"player/dob" : "1987-04-30",
	"player/id" : 48405,
	"isSR" : true,
	"player/batting-styles" : "right-hand bat",
	"player/known-as" : "Rohit Sharma",
	"fc/id" : "50844454-f8eb-4670-b54c-934e81c429a3",
	"player/pob" : "Bansod, Nagpur, Maharashtra",
	"player/country" : "INDIA"
}

export const runsInfo = [{
    "ground/name" : "Eden Gardens",
    "ground/small_name" : "Kolkata",
    "match/formatid" : 1,
    "opposition/short_name" : "West Indies",
    "match/objectid" : 676525,
    "batsman/ballsfaced" : 301,
    "series/name" : "West Indies tour of India",
    "match/startdate" : "2013-11-06T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-west-indies-2013-14",
    "notouts" : 0,
    "batsman/runs" : 177
}, {
    "ground/name" : "Wankhede Stadium",
    "ground/small_name" : "Mumbai",
    "match/formatid" : 1,
    "opposition/short_name" : "West Indies",
    "match/objectid" : 676527,
    "batsman/ballsfaced" : 127,
    "series/name" : "West Indies tour of India",
    "match/startdate" : "2013-11-14T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-west-indies-2013-14",
    "notouts" : 1,
    "batsman/runs" : 111
}, {
    "ground/name" : "The Wanderers Stadium",
    "ground/small_name" : "Johannesburg",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 648665,
    "batsman/ballsfaced" : 42,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2013-12-18T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "south-africa-v-india-2013-14",
    "notouts" : 0,
    "batsman/runs" : 14
}, {
    "ground/name" : "The Wanderers Stadium",
    "ground/small_name" : "Johannesburg",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 648665,
    "batsman/ballsfaced" : 13,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2013-12-18T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "south-africa-v-india-2013-14",
    "notouts" : 0,
    "batsman/runs" : 6
}, {
    "ground/name" : "Kingsmead",
    "ground/small_name" : "Durban",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 648667,
    "batsman/ballsfaced" : 1,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2013-12-26T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "south-africa-v-india-2013-14",
    "notouts" : 0,
    "batsman/runs" : 0
}, {
    "ground/name" : "Kingsmead",
    "ground/small_name" : "Durban",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 648667,
    "batsman/ballsfaced" : 46,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2013-12-26T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "south-africa-v-india-2013-14",
    "notouts" : 0,
    "batsman/runs" : 25
}, {
    "ground/name" : "Eden Park",
    "ground/small_name" : "Auckland",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 667651,
    "batsman/ballsfaced" : 120,
    "series/name" : "India tour of New Zealand",
    "match/startdate" : "2014-02-06T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "new-zealand-v-india-2014",
    "notouts" : 0,
    "batsman/runs" : 72
}, {
    "ground/name" : "Eden Park",
    "ground/small_name" : "Auckland",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 667651,
    "batsman/ballsfaced" : 59,
    "series/name" : "India tour of New Zealand",
    "match/startdate" : "2014-02-06T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "new-zealand-v-india-2014",
    "notouts" : 0,
    "batsman/runs" : 19
}, {
    "ground/name" : "Basin Reserve",
    "ground/small_name" : "Wellington",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 667653,
    "batsman/ballsfaced" : 3,
    "series/name" : "India tour of New Zealand",
    "match/startdate" : "2014-02-14T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "new-zealand-v-india-2014",
    "notouts" : 0,
    "batsman/runs" : 0
}, {
    "ground/name" : "Basin Reserve",
    "ground/small_name" : "Wellington",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 667653,
    "batsman/ballsfaced" : 97,
    "series/name" : "India tour of New Zealand",
    "match/startdate" : "2014-02-14T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "new-zealand-v-india-2014",
    "notouts" : 1,
    "batsman/runs" : 31
}, {
    "ground/name" : "The Rose Bowl",
    "ground/small_name" : "Southampton",
    "match/formatid" : 1,
    "opposition/short_name" : "England",
    "match/objectid" : 667715,
    "batsman/ballsfaced" : 61,
    "series/name" : "Pataudi Trophy",
    "match/startdate" : "2014-07-27T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "england-v-india-2014",
    "notouts" : 0,
    "batsman/runs" : 28
}, {
    "ground/name" : "The Rose Bowl",
    "ground/small_name" : "Southampton",
    "match/formatid" : 1,
    "opposition/short_name" : "England",
    "match/objectid" : 667715,
    "batsman/ballsfaced" : 28,
    "series/name" : "Pataudi Trophy",
    "match/startdate" : "2014-07-27T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "england-v-india-2014",
    "notouts" : 0,
    "batsman/runs" : 6
}, {
    "ground/name" : "Adelaide Oval",
    "ground/small_name" : "Adelaide",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754737,
    "batsman/ballsfaced" : 89,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2014-12-09T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 43
}, {
    "ground/name" : "Adelaide Oval",
    "ground/small_name" : "Adelaide",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754737,
    "batsman/ballsfaced" : 18,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2014-12-09T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 6
}, {
    "ground/name" : "Brisbane Cricket Ground",
    "ground/small_name" : "Brisbane",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754739,
    "batsman/ballsfaced" : 55,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2014-12-17T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 32
}, {
    "ground/name" : "Brisbane Cricket Ground",
    "ground/small_name" : "Brisbane",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754739,
    "batsman/ballsfaced" : 2,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2014-12-17T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 0
}, {
    "ground/name" : "Sydney Cricket Ground",
    "ground/small_name" : "Sydney",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754743,
    "batsman/ballsfaced" : 133,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2015-01-06T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 53
}, {
    "ground/name" : "Sydney Cricket Ground",
    "ground/small_name" : "Sydney",
    "match/formatid" : 1,
    "opposition/short_name" : "Australia",
    "match/objectid" : 754743,
    "batsman/ballsfaced" : 90,
    "series/name" : "Border-Gavaskar Trophy",
    "match/startdate" : "2015-01-06T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "australia-v-india-2014-15",
    "notouts" : 0,
    "batsman/runs" : 39
}, {
    "ground/name" : "Khan Shaheb Osman Ali Stadium",
    "ground/small_name" : "Fatullah",
    "match/formatid" : 1,
    "opposition/short_name" : "Bangladesh",
    "match/objectid" : 870729,
    "batsman/ballsfaced" : 9,
    "series/name" : "India tour of Bangladesh",
    "match/startdate" : "2015-06-10T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "bangladesh-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 6
}, {
    "ground/name" : "Galle International Stadium",
    "ground/small_name" : "Galle",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895773,
    "batsman/ballsfaced" : 24,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-12T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 9
}, {
    "ground/name" : "Galle International Stadium",
    "ground/small_name" : "Galle",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895773,
    "batsman/ballsfaced" : 16,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-12T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 4
}, {
    "ground/name" : "P Sara Oval",
    "ground/small_name" : "Colombo (PSS)",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895775,
    "batsman/ballsfaced" : 132,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-20T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 79
}, {
    "ground/name" : "P Sara Oval",
    "ground/small_name" : "Colombo (PSS)",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895775,
    "batsman/ballsfaced" : 55,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-20T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 34
}, {
    "ground/name" : "Sinhalese Sports Club",
    "ground/small_name" : "Colombo (SSC)",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895777,
    "batsman/ballsfaced" : 65,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-28T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 26
}, {
    "ground/name" : "Sinhalese Sports Club",
    "ground/small_name" : "Colombo (SSC)",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 895777,
    "batsman/ballsfaced" : 72,
    "series/name" : "India tour of Sri Lanka",
    "match/startdate" : "2015-08-28T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "sri-lanka-v-india-2015",
    "notouts" : 0,
    "batsman/runs" : 50
}, {
    "ground/name" : "Vidarbha Cricket Association Stadium",
    "ground/small_name" : "Nagpur",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 903607,
    "batsman/ballsfaced" : 28,
    "series/name" : "Freedom Trophy",
    "match/startdate" : "2015-11-25T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-south-africa-2015-16",
    "notouts" : 0,
    "batsman/runs" : 2
}, {
    "ground/name" : "Vidarbha Cricket Association Stadium",
    "ground/small_name" : "Nagpur",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 903607,
    "batsman/ballsfaced" : 39,
    "series/name" : "Freedom Trophy",
    "match/startdate" : "2015-11-25T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-south-africa-2015-16",
    "notouts" : 0,
    "batsman/runs" : 23
}, {
    "ground/name" : "Feroz Shah Kotla",
    "ground/small_name" : "Delhi",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 903609,
    "batsman/ballsfaced" : 6,
    "series/name" : "Freedom Trophy",
    "match/startdate" : "2015-12-03T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-south-africa-2015-16",
    "notouts" : 0,
    "batsman/runs" : 1
}, {
    "ground/name" : "Feroz Shah Kotla",
    "ground/small_name" : "Delhi",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 903609,
    "batsman/ballsfaced" : 1,
    "series/name" : "Freedom Trophy",
    "match/startdate" : "2015-12-03T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-south-africa-2015-16",
    "notouts" : 0,
    "batsman/runs" : 0
}, {
    "ground/name" : "Darren Sammy National Cricket Stadium",
    "ground/small_name" : "Gros Islet",
    "match/formatid" : 1,
    "opposition/short_name" : "West Indies",
    "match/objectid" : 1022597,
    "batsman/ballsfaced" : 23,
    "series/name" : "India tour of West Indies and United States of America",
    "match/startdate" : "2016-08-09T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "west-indies-v-india-2016",
    "notouts" : 0,
    "batsman/runs" : 9
}, {
    "ground/name" : "Darren Sammy National Cricket Stadium",
    "ground/small_name" : "Gros Islet",
    "match/formatid" : 1,
    "opposition/short_name" : "West Indies",
    "match/objectid" : 1022597,
    "batsman/ballsfaced" : 59,
    "series/name" : "India tour of West Indies and United States of America",
    "match/startdate" : "2016-08-09T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "west-indies-v-india-2016",
    "notouts" : 0,
    "batsman/runs" : 41
}, {
    "ground/name" : "Green Park",
    "ground/small_name" : "Kanpur",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 1030213,
    "batsman/ballsfaced" : 67,
    "series/name" : "New Zealand tour of India",
    "match/startdate" : "2016-09-22T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-new-zealand-2016-17",
    "notouts" : 0,
    "batsman/runs" : 35
}, {
    "ground/name" : "Green Park",
    "ground/small_name" : "Kanpur",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 1030213,
    "batsman/ballsfaced" : 93,
    "series/name" : "New Zealand tour of India",
    "match/startdate" : "2016-09-22T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-new-zealand-2016-17",
    "notouts" : 1,
    "batsman/runs" : 68
}, {
    "ground/name" : "Eden Gardens",
    "ground/small_name" : "Kolkata",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 1030215,
    "batsman/ballsfaced" : 12,
    "series/name" : "New Zealand tour of India",
    "match/startdate" : "2016-09-30T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-new-zealand-2016-17",
    "notouts" : 0,
    "batsman/runs" : 2
}, {
    "ground/name" : "Eden Gardens",
    "ground/small_name" : "Kolkata",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 1030215,
    "batsman/ballsfaced" : 132,
    "series/name" : "New Zealand tour of India",
    "match/startdate" : "2016-09-30T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-new-zealand-2016-17",
    "notouts" : 0,
    "batsman/runs" : 82
}, {
    "ground/name" : "Holkar Cricket Stadium",
    "ground/small_name" : "Indore",
    "match/formatid" : 1,
    "opposition/short_name" : "New Zealand",
    "match/objectid" : 1030217,
    "batsman/ballsfaced" : 63,
    "series/name" : "New Zealand tour of India",
    "match/startdate" : "2016-10-08T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "india-v-new-zealand-2016-17",
    "notouts" : 1,
    "batsman/runs" : 51
}, {
    "ground/name" : "Vidarbha Cricket Association Stadium",
    "ground/small_name" : "Nagpur",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 1122724,
    "batsman/ballsfaced" : 160,
    "series/name" : "Sri Lanka tour of India",
    "match/startdate" : "2017-11-24T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 1,
    "batsman/runs" : 102
}, {
    "ground/name" : "Feroz Shah Kotla",
    "ground/small_name" : "Delhi",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 1122725,
    "batsman/ballsfaced" : 102,
    "series/name" : "Sri Lanka tour of India",
    "match/startdate" : "2017-12-02T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 0,
    "batsman/runs" : 65
}, {
    "ground/name" : "Feroz Shah Kotla",
    "ground/small_name" : "Delhi",
    "match/formatid" : 1,
    "opposition/short_name" : "Sri Lanka",
    "match/objectid" : 1122725,
    "batsman/ballsfaced" : 49,
    "series/name" : "Sri Lanka tour of India",
    "match/startdate" : "2017-12-02T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 1,
    "batsman/runs" : 50
}, {
    "ground/name" : "Newlands",
    "ground/small_name" : "Cape Town",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 1122276,
    "batsman/ballsfaced" : 59,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2018-01-05T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 0,
    "batsman/runs" : 11
}, {
    "ground/name" : "Newlands",
    "ground/small_name" : "Cape Town",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 1122276,
    "batsman/ballsfaced" : 30,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2018-01-05T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 0,
    "batsman/runs" : 10
}, {
    "ground/name" : "SuperSport Park",
    "ground/small_name" : "Centurion",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 1122277,
    "batsman/ballsfaced" : 27,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2018-01-13T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 0,
    "batsman/runs" : 10
}, {
    "ground/name" : "SuperSport Park",
    "ground/small_name" : "Centurion",
    "match/formatid" : 1,
    "opposition/short_name" : "South Africa",
    "match/objectid" : 1122277,
    "batsman/ballsfaced" : 74,
    "series/name" : "India tour of South Africa",
    "match/startdate" : "2018-01-13T00:00:00.000Z",
    "player/id" : 48405,
    "match/urlcomponent" : "ci",
    "notouts" : 0,
    "batsman/runs" : 47
}
]
